auto_save: true
display_label_popup: true
store_data: false
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info
quick_advance_n: 30
quick_advance_little_n_scale: 10

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: auto  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: {'animal': [255, 0, 0],'person':[0,0,255],'vehicle':[0,255,0]}
shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 0, 0, 64]
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  fill_drawing: true
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10
  # show crosshair
  crosshair:
    polygon: false
    rectangle: true
    circle: false
    line: false
    point: false
    linestrip: false
    ai_polygon: false

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  merge_all_rectangles: M
  load_alt_labels: L  
  go_to_next_non_empty: Alt+PgDown
  go_to_prev_non_empty: Alt+PgUp
  forward_little_n: Shift+PgDown
  backward_little_n: Shift+PgUp  
  forward_n: Ctrl+PgDown
  backward_n: Ctrl+PgUp
  toggle_ignore_flag: X
  load_alt_0_labels: Alt+0
  load_alt_1_labels: Alt+1
  load_alt_2_labels: Alt+2
  load_alt_3_labels: Alt+3
  load_alt_4_labels: Alt+4  
  load_alt_5_labels: Alt+5
  load_alt_6_labels: Alt+6
  load_alt_7_labels: Alt+7
  load_alt_8_labels: Alt+8
  load_alt_9_labels: Alt+9    
  select_smallest_rectangle: Shift+S
  select_largest_rectangle: Shift+B
  keep_smallest_rectangle: S
  keep_largest_rectangle: B
  keep_selected_polygons: K
  duplicate_polygon: Ctrl+D
  select_all_polygons: Ctrl+A
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+Z
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: null 
  copy_filename: Ctrl+P
  remove_selected_point: [Meta+H, Backspace]

